### PR TITLE
Scidown

### PR DESCRIPTION
**Pull request by Mandarancio**
As already discussed I created a fork of hoedown to support my custom extension of markdown.
Moreover it also support `LaTeX` rendering so to avoid extending `pandoc` to support the extension.
The syntax of SciDown can be found in the [wiki](https://github.com/Mandarancio/scidown/wiki)
 
All native markdown functionality should work as before.

To make it work after switching to the new branch please run:

```
$ git submodule init  --recursive
$ git submodule update  --recursive
```

### CODE REVIEW

**Comment by fabiocolacio** [comment]
@Mandarancio 

After a little testing, I realized that the double-free error is triggered because the stylesheet that I pasted is not on my system. This still needs to be patched though :)

**Comment by Mandarancio** [comment]
Hi @fabiocolacio  thanks a lot for the feedback! I will fix the issues: YAML double free, the TOC mess and the preferences.

For exporting is still possible to print the output in form of pdf using the print menu (e.g. I always do like this when I want to save a pdf from a webpage). 
However the pdf generate from the print is very ugly (one the document is more then one page), however I agree with you that the output generated from the html (I'am actually passing the html to pandoc, not the latex)  is not alike (at all) to the html, I want to look around to see if there is any possibility to convert the css in some latex/pandoc style/template to make the pdf look like the html.

**Comment by Mandarancio** [comment]
I am not able to reproduce the double free error: If I had any random css style in the YAML header in my configuration everything still work. Am I missing something?

**Comment by Mandarancio** [comment]
For exporting "nice pdf" I did not found anything better than the `gtk_print`...  There is a commercial software called `princexml` that seems very interesting, but well is commercial and I'm not even sure it exists for linux.
Current status:
 
 - *TOC*: problem is fixed 
 - *Export*: restored print pdf
 - *Preferences window*: cleaned from useless settings

I still have to fix the double `free` but for the moment I was not able to reproduce it.

**Comment by fabiocolacio** [comment]
Okay, I will do some testing with gdb to see if I can learn more about the double-free error.

**Comment by fabiocolacio** [comment]
Okay when checking the stack trace with gdb, this is the output I get:

```
(gdb) bt
#0  0x00007ffff29e566b in raise () at /lib64/libc.so.6
#1  0x00007ffff29e7381 in abort () at /lib64/libc.so.6
#2  0x00007ffff2a2fa57 in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff2a369aa in  () at /lib64/libc.so.6
#4  0x00007ffff2a39675 in _int_free () at /lib64/libc.so.6
#5  0x0000000000420aa0 in free_meta (meta=0x7fffcc0138f0) at ../src/scidown/src/document.c:3899
#6  0x0000000000420bc7 in hoedown_document_free (doc=0x759840) at ../src/scidown/src/document.c:3921
#7  0x000000000040f3ff in marker_markdown_to_html (markdown=0xf8a9f0 "---\ntitle: Title\nauthor: Name Lastname\naffiliation: Institute\nkeywords: word1, word2, word3\nstyle: scidown_report.css\nnumbering: true\n---\n# Chapter I\n\n## Section A\n\n## Section B\n\n# Chapter II", size=191, base_folder=0x0, katex_mode=KATEX_LOCAL, highlight_mode=HIGHLIGHT_LOCAL, mermaid_mode=MERMAID_LOCAL, stylesheet_location=0xf93b00 "/usr/local/share/com.github.fabiocolacio.marker/styles/GitHub2.css")
    at ../src/marker-markdown.c:243
#8  0x0000000000412a48 in marker_preview_render_markdown (preview=0x777aa0, markdown=0xf8a9f0 "---\ntitle: Title\nauthor: Name Lastname\naffiliation: Institute\nkeywords: word1, word2, word3\nstyle: scidown_report.css\nnumbering: true\n---\n# Chapter I\n\n## Section A\n\n## Section B\n\n# Chapter II", css_theme=0xf93b00 "/usr/local/share/com.github.fabiocolacio.marker/styles/GitHub2.css", base_uri=0x0) at ../src/marker-preview.c:319
#9  0x000000000040aea2 in marker_editor_refresh_preview (editor=0x9e2160) at ../src/marker-editor.c:328
#10 0x000000000040a1eb in refresh_timeout_cb (user_data=0x9e2160) at ../src/marker-editor.c:75
#11 0x00007ffff5e315dd in g_timeout_dispatch () at /lib64/libglib-2.0.so.0
#12 0x00007ffff5e30b77 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#13 0x00007ffff5e30f20 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#14 0x00007ffff5e30fac in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#15 0x00007ffff63edcad in g_application_run () at /lib64/libgio-2.0.so.0
#16 0x0000000000409f69 in main (argc=1, argv=0x7fffffffded8) at ../src/marker.c:266
(gdb) 
```

The double-free error is happening in the ``free_meta ()`` function of ``document.c`` for scidown in line 3898. This is the block in question:

```C
	if (meta->style)
		free(meta->keywords);
```
My guess is that either ``meta->keywords`` is not being allocated to begin with, or it is being freed twice for some reason. Do you have any idea why @Mandarancio?

**Comment by Mandarancio** [comment]
Fixed, the correct code was suppose to be:

```c
if (meta->style)
    free(meta->style);
```
instead I forgot to change the name of the pointer inside the free (due to a copy paste probably).

**Comment by fabiocolacio** [comment]
Okay that fixed the double-free error for me.

The TOC problem still happens for me though (same behaviour as before).

**Comment by Mandarancio** [comment]
Could you paste an example of the two files used here so I can try to debug it?

Thanks! :)

**Comment by fabiocolacio** [comment]
I think we might be misunderstanding each other, so I will try to rephrase the problem :)

The issue I am having is that the structure of the table of contents does not match the structure of the document itself.

In the table of contents it shows:

```
2. Chapter II
    2.1 Features
    2.2 Screenshots
    2.3 Packages
    2.4 Installation from source
        2.4.1 Dependencies
        2.4.2 Build Instructions
    2.5 Donations/Tips
```

But when you scroll down, the document is *actually* structured like this:

```
2. Chapter II
3. Marker
    3.1 Features
    3.2 Screenshots
    3.3 Packages
    3.4 Installation from source
        3.4.1 Dependencies
        3.4.2 Build Instructions
    3.5 Donations/Tips
```

In other words, the numbering for the table of contents does not match the numbering of the document. Also, the entry for *Marker* is missing from the table of contents entirely.

If this is intentional, I'm having trouble understanding why it is like this.

**Comment by Mandarancio** [comment]
Fixed! The problem was with the headers on the first line of the documents were not recognized by the TOC generator.

Now I will add the headerline to the TOC as well:

```markdown
Title
====

Section
---------
```

**Comment by fabiocolacio** [comment]
This fixed it, thanks.

All the issues seem to be resolved so I am merging this now. Good work!

**Pull request merged**
