### PR TITLE
Patch to syntax theme bug

### LINKED ISSUE #71: Editor Syntax theme is not stored
On my archlinux and on the last version of the code the editor syntax theme is not correctly stored and restored. After closing is restored to _tango_.

### PR DESCRIPTION
**Pull request by Mandarancio**
To close #71  I propose this simple patch.
However again as in #69  I suggest to split the setting in 2 parts, a toggled button to enable/disable the theme and a combo-box to select the theme.
It would be more clear and more simple to code. 
 
As well I would like to become member of the Marker project, in this way I could avoid all this pull requests.

### CODE REVIEW

**Comment by fabiocolacio** [comment]
We can re-implement the toggle button, but I would like it to be in the same style as gedit's preferences as shown below:

The toggle button should be on the same line as the combo box, and when the toggle button is off, the combo-box should not be modifiable.

gedit-prefs1

gedit-prefs2

**Comment by fabiocolacio** [comment]
Also I have added you as a collaborator. Your help has been invaluable, and you have proven to me that you know what you are doing, and that you can be trusted.

Thanks, and welcome to the team!

**Comment by Mandarancio** [comment]
Thank you very much for the trust.

I think as well this will be the more rational solution for toggled plus extra options on the same line. Do you use any graphical editor for the ui?

**Comment by Mandarancio** [comment]
Can I merge my other pull requests or I wait your approval?

**Comment by fabiocolacio** [comment]
I'd like to test out the the WebExtension PR before merging it, but the other two can be merged.

**Comment by fabiocolacio** [comment]
For the .ui files I often use Glade. Glade doesn't have support for every kind of widget (such as the shortcuts window, which I am working on in my local branch). For those, I just use a text editor.

**Pull request merged**
