### PR TITLE
Figure Caption and Numbering added to Hoedown

### PR DESCRIPTION
**Pull request by Mandarancio**
I added a small feature to hoedown to display the title or the alt text of an image as caption:
```markdown
Image with title:
![alt text](path/to/image "title")

Image with only alt text:
![alt text](path/to/image)
```
Moreover I added the option to numbering the figure (and use the number as id of the html block).

figure_captioning_num
**Figure caption and numbering enabled**

figure_caption
**Figure caption enabled, numbering disabled**

figure_no_caption
**Figure caption and numbering disabled**

To nicely render the caption I modified some (or all?) css theme to align the figure caption to the centre and use a smaller font.

### CODE REVIEW

**Comment by fabiocolacio** [comment]
I like this feature but I have a few suggestions:

First of all, I think it should be possible to have figure numbers without captions. This way it will just say Figure 1, Figure 2, etc. with no caption.

Also, instead of changing each CSS file, I think it would be better if the CSS rule was inline with ``<style>`` tags. This way, It will work on any CSS theme (even if the user has a custom one), and it will be easier to maintain.

**Comment by Mandarancio** [comment]
Well I think for better modularity and as well cleaner code the style should be left to the css (as the modification is minimal)  and as well depending from the css chosen the font-size should be different (to fit with the style, as some css have default font-size 12px and other 14px).

The additional css is just:
```
figure figcaption {
text-align: center;
font-size: 10px;
} 
```
And even without this css the caption works (is just left aligned).

For the first suggestion I think is already implemented (as if no title or alt text is found it will just show "figure N:") however I'm improving it (removing the ":" when not needed) and as well adding possible future translation of "figure".

**Comment by Mandarancio** [comment]
This is the current behaviour when caption and numbering is enabled:

**Image with no title or alt text**
figure_no_alt_no_title

**Image with alt text and no title**
figure_no_title_alt

**Image with title and alt text**
figure_title_and_alt

If this is the behaviour you want please merge ;)

**Comment by fabiocolacio** [comment]
Ah okay, I see now. I will merge it 👍

**Pull request merged**
