### PR TITLE
WebExtension to keep scroll position fixed

### PR DESCRIPTION
**Pull request by Mandarancio**
Simple web extension to fix to issue #13

### CODE REVIEW

**Comment by Mandarancio** [comment]
As written in the comment in the extension there is a bug or in the initialization of the extension or in webkit2gtk that cause a **SIGSEGV** after closing Marker (the event happen after the return in the main). 
This happen even with an empty extension or with a static library (I'm using a shared one), if you have any suggestion please let me know!

**Comment by fabiocolacio** [comment]
When testing this, it doesn't seem to work if I am typing fast. This is probably because it refreshes with every keystroke, and I don't think there is much we can do besides slowing down the refresh rate.

**Comment by fabiocolacio** [comment]
Also there seems to be a glitch where the extension fails to load sometimes. If I open a long document to test this out, sometimes it will keep my place, and other times will will scroll to the top on my first keystroke. I will merge this for now, as it doesn't harm anything, but it needs some improvement. I will open a new issue for this problem as well

**Comment by Mandarancio** [comment]
I will merge the branch to the new autoscroll branch I added to your repo so I can delete my fork

**Pull request merged**
