### PR TITLE
Sidebar for multiple file editing 

### PR DESCRIPTION
**Pull request by Mandarancio**
This is the first addition to improve the interface for working with multiple documents (#47).

sidebar
 
Trough the sidebar is possible to select the current document, rename and close documents.
Few short-cuts have been added (also to the short-cuts dialog) to create new windows, open documents in a new window etc.

### CODE REVIEW

**Comment by fabiocolacio** [comment]
Great work as always!

I have a few small suggestions:

1. When there is an unsaved document, the sidebar title does not show indication that there are unsaved changes.
2. Why does ``MarkerEditor`` need the ``title`` variable? Can't you just call ``marker_editor_get_title ()`` or is there something I am missing? This would also solve 1. because ``marker_editor_get_title ()`` shows if there are unsaved changes.
3. When I open multiple files at once either through the command line or through nautilus, it opens multiple windows. I think it would be best if they all open in the same window.
4. When I click on the filename in the sidebar, it tries to rename the document. This is a good feature, but it shouldn't trigger on a single click. It should either be from a double click or from a contextual menu of some sort.

Again they are very minor issues but those are my thoughts.

**Comment by Mandarancio** [comment]
1. That's right, I forgot to implement it but it should be pretty easy to do so.
2. Otherwise blank documents (not linked to a file) can not have different name from "Untitled.md"
3. I will look into it
4. Yes double click will be definitely better!

**Comment by Mandarancio** [comment]
@fabiocolacio the point 1, 3 and 4 should be solved and I already explain point 2. Try it now and tell me if it's ok :)

**Comment by fabiocolacio** [comment]
Thanks. It is merged now :)

**Pull request merged**
